### ISSUE TITLE
Interrupts, async detection of clicks, rotations

### ISSUE THREAD

**Issue by Derion23** [Derion23/ColtShot#2]
Hi, ich hab mir gedacht, dass wir eine asynchrone Erkennung für den Drehknopf brauchen. Jetzt funktioniert das Programm so, dass das Programm im loop() so schnell wie es geht den Status der digitalen Pins ausliest. Das funktioniert auch ganz ok, falls man nur das im loop() macht. 
Falls man aber viele Sachen im loop hat, was wir später haben werden, funktioniert das wahrscheinlich nicht gut. Falls der Arduino dann nämlich mit anderen Codezeilen beschäftigt ist, während man den Knopf dreht oder drückt, dann erkennt er dies vielleicht nicht.
Ich habe gesehen, dass man die Erkennung auch asynchron über interrupts lösen kann.
Könnte sich jemand damit beschäftigen wie man das auf dem Arduino implementieren kann, und inwiefern wir das benötigen?
Danke schonmal :-)

**Comment by Timmi315** [comment]
mach ich gerne, hab ich schon öfters gemacht :) Die Eingaben dann einfach in ne queue rein, oder? Hocke ich mich gerne Montag oder so ran, am WE hab ich net wirklich viel Zeit...
(Also außer jmd anderes hätte voll Bock sich da reinzulesen und würde es viel lieber selber machen ^^)

**Comment by Derion23** [comment]
Danke Timo das wär super 👍 
Dann schau ich mal, dass ich über das WE eine Graphische Interface und ein paar Menüs auf den Arduino bekomm
